#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "facette"
name = "Facette"
description.en = "Time series data visualization"
description.fr = "Visualisation de données de séries chronologiques"

version = "0.5.1~ynh3"

maintainers = ["rafi59"]

[upstream]
license = "BSD-3-Clause"
website = "https://facette.io/"
demo = "https://play.facette.io/browse/"
admindoc = "https://docs.facette.io/"
code = "https://github.com/facette/facette"

[integration]
yunohost = ">= 11.2"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"
disk = "50M"
ram.build = "200M"
ram.runtime = "200M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    amd64.url = "https://github.com/facette/facette/releases/download/0.5.1/facette_0.5.1_linux_amd64.tar.gz"
    amd64.sha256 = "152d8889da545733f25ea197208f1edd7c07cfee063b44b3ac55b61d61d361e4"
    armhf.url = "https://github.com/facette/facette/releases/download/0.5.1/facette_0.5.1_linux_arm.tar.gz"
    armhf.sha256 = "f9b8f90342b342523365e483299dbe684d281f7595e99efbcdf2789ce4e0609b"
    arm64.url = "https://github.com/facette/facette/releases/download/0.5.1/facette_0.5.1_linux_arm64.tar.gz"
    arm64.sha256 = "54039a821567928a2bc39b4d9620a5c148215c1c9a47be63a1f3cace7371420b"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = ".*_linux_amd64.tar.gz"
    autoupdate.asset.arm64 = ".*_linux_arm64.tar.gz"
    autoupdate.asset.armhf = ".*_linux_arm.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 12003

    [resources.apt]
    packages = ["rrdtool", "rrdcached", "collectd", "mariadb-server"]

    [resources.database]
    type = "mysql"
